apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: backend
spec:
  selector:
    app: backend
  ports:
  - protocol: TCP
    port: 80       
    targetPort: 3000 
    nodePort: 30001  
  type: NodePort
